version: "3.4"
services:
    db-master-1:
        image: mysql:8.4
        environment:
            MYSQL_DATABASE: example_db
            MYSQL_ROOT_PASSWORD: Gh8[$qVo{[Nz
        ports:
            - 3307:3306
        volumes:
            - ./mysql-data-master-1:/var/lib/mysql
            - ./conf/my-master-1.conf:/etc/mysql/conf.d/my.cnf
    db-slave-1:
        image: mysql:8.4
        environment:
            MYSQL_DATABASE: example_db
            MYSQL_ROOT_PASSWORD: '4kjB$IQJGi,:'
        ports:
            - 3308:3306
        volumes:
            - ./mysql-data-slave-1:/var/lib/mysql
            - ./conf/my-slave-1.conf:/etc/mysql/conf.d/my.cnf
    db-slave-2:
        image: mysql:8.4
        environment:
            MYSQL_DATABASE: example_db
            MYSQL_ROOT_PASSWORD: '[sx^)5,YN/Kr'
        ports:
            - 3309:3306
        volumes:
            - ./mysql-data-slave-1:/var/lib/mysql
            - ./conf/my-slave-2.conf:/etc/mysql/conf.d/my.cnf
