version: "3.4"
services:
    db-master-1:
        image: mysql:8.4
        command: --server-id=1 --log-bin=mysql-bin --binlog-format=row
        container_name: db-master-1
        environment:
            MYSQL_DATABASE: example_db
            MYSQL_ROOT_PASSWORD: 9fUcd2^=;V]M
        ports:
            - 3307:3306
        volumes:
            - ./data/mysql-data-master-1:/var/lib/mysql
    db-slave-1:
        image: mysql:8.4
        command: --server-id=2 --log-bin=mysql-bin --binlog-format=row
        container_name: db-slave-1
        environment:
            MYSQL_DATABASE: example_db
            MYSQL_ROOT_PASSWORD: R<QU7HV>WT0{
        ports:
            - 3308:3306
        volumes:
            - ./data/mysql-data-slave-1:/var/lib/mysql
    db-slave-2:
        image: mysql:8.4
        command: --server-id=3 --log-bin=mysql-bin --binlog-format=row
        container_name: db-slave-2
        environment:
            MYSQL_DATABASE: example_db
            MYSQL_ROOT_PASSWORD: KqmO7Gn{//zb
        ports:
            - 3309:3306
        volumes:
            - ./data/mysql-data-slave-2:/var/lib/mysql
